### PR TITLE
Update Current-Chapters.csv

### PR DESCRIPTION
**Pull request by chucheria**
Add 
 - 62bc4310708206778fd35aaee34e0167089630cf 
 - 80a82678986c81fcc96d4b21253a5438b6269c33
 - GitHub Sydney

### CODE REVIEW

**Comment by ledell** [comment]
The usual way is to put Washington as the city and D.C. or District of Columbia as the state

**Comment by lauracion** [comment]
I tried but was not able to put time on this. LatinR is taking most of me these days. Whenever the switch to .csv is ready, please say the word and I'll catch up with onboarding asap. TY!

**Comment by ledell** [comment]
@chucheria @gdequeiroz I made the change to Washington, D.C.  I think it's good to go now.

**Comment by chucheria** [comment]
Thanks for edit the file @ledell ! I think there has been no more changes in the master MD file, there are a couple of PR for the MD but can be done directly here.

**Pull request merged**
