### PR TITLE
Add information on how to add videos to the YouTube channel

### PR DESCRIPTION
**Pull request by Athanasiamo**
Added a single markdown file with information about the procedure to add a video to the youtube channel.

### CODE REVIEW

**Comment by maelle** [comment]
oh good! Is it fine if I review this once I have the book skeleton within the next few weeks? Thank you in any case!

**Comment by Athanasiamo** [comment]
sure! No problem. I can point people to my version for now untill you have the time 👍

**Comment by maelle** [comment]
Thank you!!
Up at last! https://r-ladies-guide.netlify.app/organization/youtube/
Source https://github.com/rladies/rladiesguide/tree/main/content/organization/youtube

What is maybe missing are images. In any case feel free to open a PR/issue.

Regarding the starter-kit repo I was thinking it should link to rladiesguide (once it has a subdomain) instead of containing the guidance, but we'll see.

**Comment by maelle** [comment]
@Athanasiamo can I close this PR since the content is in the rladiesguide?

**Comment by Athanasiamo** [comment]
All good!

**Pull request closed without merging**
