### PR TITLE
Correct maggie@rladies.org for gmail settings

### PR DESCRIPTION
**Pull request by ChrisZasa**
Update of smtp, port and SSL setting
picture gmail4 and gmail8 replacements

### CODE REVIEW

**Comment by yabellini** [comment]
Looks fine!

**Comment by ChrisZasa** [comment]
Thanks for the review @yabellini  .... somehow something isn't fitting... I checked the wiki and can't see the updated screenshots. I'll have a look in the afternoon

**Comment by ChrisZasa** [comment]
Corrected the file name in the wiki page, screenshots are updated including the maggie@gmail.com address... Job is done :) @yabellini @ledell

**Comment by yabellini** [comment]
Thank you @ChrisZasa !!

**Pull request merged**
