### PR TITLE
add gh actions to create jsons for the website 

### PR DESCRIPTION
**Pull request by Athanasiamo**
the website uses current-chapters, global-team and global-team-alumni data.
To make a move to hugo data templates, the most convenient data format is json. 

Here I add an action that will write jsons based on the csv's into the `jsons` folder, which then the webpage can use.

### CODE REVIEW

**Comment by Athanasiamo** [comment]
sorry for messy commits, there was some trial and error to get the kinks out of the workflows.

**Review by maelle — COMMENTED** [review]
Awesome!

My only question would be, why not ditch the CSVs entirely? I reckon it'd be work in other places but I'm now wondering what the easiest format for editing is.

**Comment by Athanasiamo** [comment]
I think people might be more comfortable with tabular data than jsons? Atleast I would be less apprehensive about editing tabular data than jsons. Even now, when I'm starting to get more comfy with tabular data, I would still be more afraid of adding to the chapters if I were to edit the jsons directly.

We might benefit from more feedback from others on this. Maybe we can ask organisers to input their opinions? 

And dont merge it yet anyway, I should make the chapters organisers into an array!

**Comment by Athanasiamo** [comment]
I have also been thinking that we dont need the full paths to accounts for twitter, instagram, youtube etc, we just need the account names. That would make the whole file tidier, tabular or json.

**Comment by maelle** [comment]
@Athanasiamo is this still needed?

**Comment by Athanasiamo** [comment]
no, I switched it all to use meetupr and the csv directly in the CI. So I'll go ahead and close. Thanks for the prompt

**Pull request closed without merging**
