### PR TITLE
Current chapters

### PR DESCRIPTION
**Pull request by chucheria**
I finished writting all the chapters. I checked the repos of every chapter (column GitHub) and the social media, but I suppose some information is missing.

Also, I am working on a script to modify this file from the command line, maybe other way is better (like a shiny app?) but this is the fastest for me to code it.

### CODE REVIEW

**Comment by ledell** [comment]
> Also, I am working on a script to modify this file from the command line, maybe other way is better (like a shiny app?) but this is the fastest for me to code it.

@chucheria Talk with @gdequeiroz and @lauracion about what would work best for them as they are the main people who add/edit this metadata.  I think Gabi was planning on making edits right in the Github UI.

**Comment by lauracion** [comment]
Hi, editing the .csv file directly on the github ui is a good way to add this metadata for me.

**Comment by gdequeiroz** [comment]
Looks good to me!

**Comment by chucheria** [comment]
Great, I'll leave the editing part and merge. Thanks everyone!

**Comment by gdequeiroz** [comment]
@chucheria Let us know when we are good to make the transition from the md to the csv file.

**Comment by chucheria** [comment]
@gdequeiroz I think you can start now. I'd review the file anyway, you and @lauracion know the chapters better.

**Pull request merged**
