### PR TITLE
Update Frankfurt

### PR DESCRIPTION
**Pull request by sandrapintor**
This file includes an update to R-Ladies Frankfurt contacts and organizers

### CODE REVIEW

**Comment by gdequeiroz** [comment]
Hi @sandrapintor, it looks like your PR changed the whole `.csv` file. To be safe, can you let me know what you changed?

**Comment by sandrapintor** [comment]
Hi @gdequeiroz, I changed just the information related to the Frankfurt row (State.Region, Twitter, Github, Organizers). If you think it's better, I can change the file again and make a new pull request

**Comment by gdequeiroz** [comment]
Sure, it works for me. Thank you!

**Comment by cvitolo** [comment]
Hi @sandrapintor, thanks for submitting the changes. I'm going to close this issue now because the entries for Frankfurt were updated in the last commit to master.

**Pull request closed without merging**
