### PR TITLE
update chapter RLadies_Qro

### PR DESCRIPTION
**Pull request by azaleara**
Update of RLadies_Qro's mail, periscope, GitHub and slack

### CODE REVIEW

**Comment by cvitolo** [comment]
Hi @azaleara , thanks for submitting the changes, however I noticed some conflicts:

- the email address we have is queretaro@rladies.org, but you changed it to qro@rladies.org... which is the correct one?

- you used https://github.com/RladiesQro in place of your website (I assume this was a mistake)

**Comment by cvitolo** [comment]
I added links to periscope, github and twitter to master, however email is still conflicting. please advice!

**Comment by azaleara** [comment]
I see, It was a mistake. I will delete R_Ladies_Qro website because we don't have it, and the mail is qro@rladies.org :)

**Comment by azaleara** [comment]
Thanks @cvitolo :)

**Comment by cvitolo** [comment]
Thanks a lot for clarifying @azaleara, we will deactivate the unused email (queretaro@rladies.org).
I implemented the changes directly in master. Closing this PR.

**Pull request closed without merging**
